In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import ast

filepath = r"C:\Users\jjap2\Poleto SCE\Poleto-SCE\dond_game_data.csv"
df = pd.read_csv(filepath)

In [ ]:
# This cell excludes postgame offers
# Needed for when creating banker thanks to the articles relevant to functions of the banker in deal or no deal
# Should result in a count of 730, otherwise something is wrong
df = df[df["Postgame"] != 1]

,Game ID,Round,Board Value,Board Average,Board Balance,Previous Offer,Offer,Offer Percent of Average,Deal,Amount Won,Postgame,Probability of Big Value
count,730.000000,730.000000,7.300000e+02,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.0,730.000000
mean,56.736986,4.234247,1.376281e+06,139340.102740,7.601316,57832.630521,73028.369603,0.538346,0.139726,15747.883562,0.0,0.263949
std,29.864199,2.337428,1.112492e+06,99363.031481,58.123859,67729.969565,77235.916677,0.290711,0.346940,57284.402922,0.0,0.145753
min,1.000000,1.000000,1.000000e+02,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,33.000000,2.000000,5.004275e+05,72972.250000,0.510250,12000.000000,22000.000000,0.303750,0.000000,0.000000,0.0,0.182000
50%,56.500000,4.000000,1.139690e+06,129899.000000,0.947000,38000.000000,49000.000000,0.529250,0.000000,0.000000,0.0,0.250000
75%,83.000000,6.000000,2.097326e+06,186457.250000,1.931500,77000.000000,96750.000000,0.766000,0.000000,0.000000,0.0,0.333000
max,107.000000,10.000000,8.031161e+06,850150.000000,1450.590000,650000.000000,675000.000000,1.400000,1.000000,675000.000000,0.0,0.750000

In [ ]:
# This cell excludes when offers = 0
# AKA when contestants stick with their cases and don't switch
# count = 717
df = df[df["Offer"] != 0]

,Game ID,Round,Board Value,Board Average,Board Balance,Previous Offer,Offer,Offer Percent of Average,Deal,Amount Won,Postgame,Probability of Big Value
count,717.000000,717.000000,7.170000e+02,717.000000,717.000000,717.000000,717.000000,717.000000,717.000000,717.000000,717.0,717.000000
mean,56.704324,4.129707,1.399757e+06,141127.945607,7.587536,58200.495509,74352.454407,0.548107,0.124128,15736.178522,0.0,0.266643
std,29.933150,2.224463,1.108329e+06,98444.205329,58.525724,67222.547925,77298.838719,0.284060,0.329958,57601.036072,0.0,0.142884
min,1.000000,1.000000,1.000000e+02,34.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,33.000000,2.000000,5.122010e+05,75284.000000,0.536000,14000.000000,24000.000000,0.318300,0.000000,0.000000,0.0,0.200000
50%,57.000000,4.000000,1.150455e+06,130891.000000,0.962000,39000.000000,51000.000000,0.534900,0.000000,0.000000,0.0,0.250000
75%,83.000000,6.000000,2.117940e+06,187434.000000,1.963000,78000.000000,97000.000000,0.776600,0.000000,0.000000,0.0,0.333000
max,107.000000,9.000000,8.031161e+06,850150.000000,1450.590000,650000.000000,675000.000000,1.400000,1.000000,675000.000000,0.0,0.750000

In [ ]:
# This cell splits remaining values into a string, unsure if this is needed yet
# RUN ONLY IF NEEDED
# Convert "Remaining Values" from string to list
df["Remaining Values"] = df["Remaining Values"].apply(ast.literal_eval)

# Extract unique values
all_values = set()
for values in df["Remaining Values"]:
    all_values.update(values)

for value in sorted(all_values):
    df[f"Case_{value}"] = df["Remaining Values"].apply(lambda x: 1 if value in x else 0)

- Should be able to do simple linear regression with just excluding postgame and offer=0
- Extracting remaining values likely needed for simulations/game display if we go that route